package(default_visibility = ["//visibility:public"])

proto_library(
    name = "game_log_proto",
    srcs = ["game_log.proto"],
)

java_proto_library(
    name = "game_log_java_proto",
    deps = [":game_log_proto"],
)
