perspective: PLAYER
script: TROUBLE_BREWING
players: "Neldor"
players: "Elmon"
players: "Raibyn"
players: "Haera"
players: "Tanila"
players: "Ivaran"
players: "Jaonos"
events {
  night: 1
}
events {
  storyteller_interaction {
    player: "Raibyn"
    shown_token: MONK
  }
}
events {
  day: 1
}
# All players hardclaim round-robin, starting from Tanila.
events {
  claim {
    player: "Tanila"
    role: SAINT
  }
}
events {
  claim {
    player: "Ivaran"
    role: UNDERTAKER
  }
}
events {
  claim {
    player: "Jaonos"
    role: BUTLER
  }
}
events {
  claim {
    player: "Neldor"
    role: LIBRARIAN
  }
}
events {
  claim {
    player: "Elmon"
    # This will be double-claimed by Haera.
    role: INVESTIGATOR
  }
}
events {
  claim {
    player: "Raibyn"
    role: MONK
  }
}
events {
  claim {
    player: "Haera"
    role: INVESTIGATOR
  }
}
events {
  claim {
    player: "Jaonos"
    role_action {
      acting: BUTLER
      players: "Ivaran"
    }
  }
}
events {
  claim {
    player: "Neldor"
    role_action {
      acting: LIBRARIAN
      players: "Elmon"
      players: "Raibyn"
      roles: DRUNK
    }
  }
}
events {
  claim {
    player: "Elmon"
    role_action {
      acting: INVESTIGATOR
      players: "Jaonos"
      players: "Neldor"
      roles: BARON
    }
  }
}
events {
  claim {
    player: "Haera"
    role_action {
      acting: INVESTIGATOR
      players: "Neldor"
      players: "Elmon"
      roles: BARON
    }
  }
}
# Neldor is in two pings, but Elmon and Haera are double-claiming.
events {
  nomination {
    nominator: "Haera"
    nominee: "Elmon"
  }
}
events {
  vote {
    num_votes: 4
    on_the_block: "Elmon"
  }
}
events {
  execution: "Elmon"
}
events {
  death: "Elmon"
}
events {
  night: 2
}
events {
  storyteller_interaction {
    player: "Raibyn"
    role_action {
      acting: MONK
      players: "Ivaran"
    }
  }
}
events {
  day: 2
}
# Storyteller announces that Ivaran died in the night.
events {
  night_death: "Ivaran"
}
events {
  claim {
    player: "Jaonos"
    role_action {
      acting: BUTLER
      players: "Ivaran"
    }
  }
}
# Raibyn claims to have protected Ivaran, but Ivaran still died.
events {
  claim {
    player: "Raibyn"
    role_action {
      acting: MONK
      players: "Ivaran"
    }
  }
}
# There are 3 possible worlds, one for each demon.