package(default_visibility = ["//visibility:public"])

java_library(
    name = "game_lib",
    srcs = glob(["*.java"]),
    deps = [
       "@com_google_protobuf//:protobuf_java",
       "//src/main/proto:game_log_java_proto",
    ],
)
