perspective: OBSERVER
setup {
  players: "Neldor"
  players: "Elmon"
  players: "Raibyn"
  players: "Haera"
  players: "Tanila"
  players: "Ivaran"
  players: "Jaonos"
}
events {
  night: 1
}
events {
  day: 1
}
# All players hardclaim round-robin, starting from Tanila.
events {
  claim {
    player: "Tanila"
    role: SAINT
  }
}
events {
  claim {
    player: "Ivaran"
    role: UNDERTAKER
  }
}
events {
  claim {
    player: "Jaonos"
    role: BUTLER
    info {
      butler_action: "Ivaran"
    }
  }
}
events {
  claim {
    player: "Neldor"
    role: LIBRARIAN
    info {
      librarian_info {
        ping1: "Elmon"
        ping2: "Raibyn"
        role: DRUNK
      }
    }
  }
}
events {
  claim {
    player: "Elmon"
    # This will be double-claimed by Haera.
    role: INVESTIGATOR
    info {
      investigator_info {
        ping1: "Jaonos"
        ping2: "Neldor"
        role: BARON
      }
    }
  }
}
events {
  claim {
    player: "Raibyn"
    role: MONK
  }
}
events {
  claim {
    player: "Haera"
    role: INVESTIGATOR
    info {
      investigator_info {
        ping1: "Neldor"
        ping2: "Elmon"
        role: BARON
      }
    }
  }
}
# Neldor is in two pings, but Elmon and Haera are double-claiming.
events {
  nomination {
    nominator: "Haera"
    nominee: "Elmon"
  }
}
events {
  vote {
    votes: "Raibyn"
    votes: "Haera"
    votes: "Tanila"
    votes: "Ivaran"
    votes: "Jaonos"
    votes: "Neldor"
    votes: "Elmon"
    on_the_block: "Elmon"
  }
}
events {
  execution: "Elmon"
}
events {
  death: "Elmon"
}
events {
  night: 2
}
events {
  day: 2
}
# Storyteller announces that Ivaran died in the night.
events {
  death: "Ivaran"
}
events {
  claim {
    player: "Jaonos"
    info {
      butler_action: "Ivaran"
    }
  }
}
# Raibyn claims to have protected Ivaran, but Ivaran still died.
events {
  claim {
    player: "Raibyn"
    info {
      butler_action: "Ivaran"
    }
  }
}
# This narrows down the worlds considerably for Good, allowing them
# to kill the two outsiders who are messing up the count.
# Are other worlds even possible here?