perspective: STORYTELLER
setup {
  players: "Neldor"
  players: "Elmon"
  players: "Raibyn"
  players: "Haera"
  players: "Tanila"
  players: "Ivaran"
  players: "Jaonos"
  # Actually has 2 outsiders instead of 0 because of Baron.
  player_roles {
    key: "Neldor"
    value: LIBRARIAN
  }
  player_roles {
    key: "Elmon"
    value: BARON
  }
  player_roles {
    key: "Raibyn"
    value: DRUNK
  }
  player_roles {
    key: "Haera"
    value: INVESTIGATOR
  }
  player_roles {
    key: "Tanila"
    value: IMP
  }
  player_roles {
    key: "Ivaran"
    value: UNDERTAKER
  }
  player_roles {
    key: "Jaonos"
    value: BUTLER
  }
}
events {
  night: 1
}
events {
  storyteller_interaction {
    player: "Neldor"
    shown_token: LIBRARIAN
  }
}
events {
  storyteller_interaction {
    player: "Elmon"
    shown_token: BARON
  }
}
events {
  storyteller_interaction {
    player: "Raibyn"
    shown_token: MONK
  }
}
events {
  storyteller_interaction {
    player: "Haera"
    shown_token: INVESTIGATOR
  }
}
events {
  storyteller_interaction {
    player: "Tanila"
    shown_token: IMP
  }
}
events {
  storyteller_interaction {
    player: "Ivaran"
    shown_token: UNDERTAKER
  }
}
events {
  storyteller_interaction {
    player: "Jaonos"
    shown_token: BUTLER
  }
}
events {
  storyteller_interaction {
    player: "Elmon"
    minion_info {
      demon: "Tanila"
    }
  }
}
events {
  storyteller_interaction {
    player: "Tanila"
    demon_info {
      minions: "Elmon"
      bluffs: SAINT
      bluffs: SLAYER
      bluffs: EMPATH
    }
  }
}
events {
  storyteller_interaction {
    player: "Neldor"
    role_action {
      librarian_info {
        ping1: "Elmon"
        ping2: "Raibyn"
        role: DRUNK
      }
    }
  }
}
events {
  storyteller_interaction {
    player: "Haera"
    role_action {
      investigator_info {
        ping1: "Neldor"
        ping2: "Elmon"
        role: BARON
      }
    }
  }
}
events {
  storyteller_interaction {
    player: "Jaonos"
    role_action {
      butler_action: "Ivaran"
    }
  }
}
events {
  day: 1
}
# All players hardclaim round-robin, starting from Tanila.
events {
  claim {
    player: "Tanila"
    role: SAINT
  }
}
events {
  claim {
    player: "Ivaran"
    role: UNDERTAKER
  }
}
events {
  claim {
    player: "Jaonos"
    role: BUTLER
    info {
      butler_action: "Ivaran"
    }
  }
}
events {
  claim {
    player: "Neldor"
    role: LIBRARIAN
    info {
      librarian_info {
        ping1: "Elmon"
        ping2: "Raibyn"
        role: DRUNK
      }
    }
  }
}
events {
  claim {
    player: "Elmon"
    # This will be double-claimed by Haera.
    role: INVESTIGATOR
    info {
      investigator_info {
        ping1: "Jaonos"
        ping2: "Neldor"
        role: BARON
      }
    }
  }
}
events {
  claim {
    player: "Raibyn"
    role: MONK
  }
}
events {
  claim {
    player: "Haera"
    role: INVESTIGATOR
    info {
      investigator_info {
        ping1: "Neldor"
        ping2: "Elmon"
        role: BARON
      }
    }
  }
}
# Neldor is in two pings, but Elmon and Haera are double-claiming.
# Good gets lucky and chooses to vote out Elmon.
events {
  nomination {
    nominator: "Haera"
    nominee: "Elmon"
  }
}
events {
  vote {
    votes: "Raibyn"
    votes: "Haera"
    votes: "Tanila"
    votes: "Ivaran"
    votes: "Jaonos"
    votes: "Neldor"
    votes: "Elmon"
    on_the_block: "Elmon"
  }
}
events {
  execution: "Elmon"
}
events {
  death: "Elmon"
}
events {
  night: 2
}
events {
  storyteller_interaction {
    player: "Raibyn"
    role_action {
      # This happens even though Raibyn is drunk and there is no effect.
      monk_action: "Ivaran"
    }
  }
}
events {
  storyteller_interaction {
    player: "Tanila"
    role_action {
      # Tanila chooses to kill the Undertaker, because she knows Raibyn is drunk.
      imp_action: "Ivaran"
    }
  }
}
events {
  storyteller_interaction {
    player: "Jaonos"
    role_action {
      # Jaonos doesn't know his master is dead.
      butler_action: "Ivaran"
    }
  }
}
events {
  day: 2
}
# Storyteller announces that Ivaran died in the night.
events {
  death: "Ivaran"
}
events {
  claim {
    player: "Jaonos"
    info {
      butler_action: "Ivaran"
    }
  }
}
# Raibyn claims to have protected Ivaran, but Ivaran still died.
events {
  claim {
    player: "Raibyn"
    info {
      butler_action: "Ivaran"
    }
  }
}
# This narrows down the worlds considerably for Good, allowing them
# to kill the two outsiders who are messing up the count.
# Are other worlds even possible here?